### ISSUE TITLE
Solution Template Plan Creation: FileNotFoundError: [Errno 2] No such file or directory: 'sample_app\\ma_config.json'

### ISSUE THREAD

**Issue by dciborow** [microsoft/az-partner-center-cli#66]
```shell
(base) PS C:\Users\djc39\AGAI-Industrial-AI\azure\game-dev-vm> azpc st plan create --name $name --plan_name $plan_name
Traceback (most recent call last):
  File "c:\users\djc39\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\djc39\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\djc39\miniconda3\Scripts\azpc.exe\__main__.py", line 7, in <module>
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\azpc_app.py", line 37, in main
    return run(commands[subgroup]())
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\__init__.py", line 44, in run
    output = commands[command]()
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\__init__.py", line 78, in run_plan
    return commands[plan_command]()
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\plan.py", line 201, in create
    return self.submission_type(args.plan_name, args.name, subtype=args.subgroup).create()
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\plan.py", line 63, in create
    self.update()
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\plan.py", line 71, in update
    self._update_plan_listing()
  File "c:\users\djc39\miniconda3\lib\site-packages\azureiai\partner_center\plan.py", line 123, in _update_plan_listing
    with open(Path(self.app_path).joinpath(self.json_listing_config), "r", encoding="utf8") as read_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sample_app\\ma_config.json'
```

**Comment by dciborow** [comment]
these should now be resolved.
